import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const site = path.join(root, 'site');
const logo = 'https://www.axante.it/wp-content/uploads/2021/08/axante-logo.png';

const navItems = [
  ['/', 'Home', 'home'],
  ['/servizi', 'Servizi', 'servizi'],
  ['/portfolio', 'Portfolio', 'portfolio'],
  ['/chi-siamo', 'Chi siamo', 'chi-siamo'],
  ['/contatti', 'Contatti', 'contatti']
];

const whatsappIcon = `<svg viewBox="0 0 32 32" aria-hidden="true"><path fill="#fff" d="M16 4a12 12 0 0 0-10.2 18.3L4 28l5.9-1.7A12 12 0 1 0 16 4Zm0 21.8c-1.8 0-3.5-.5-5-1.3l-.4-.2-3.5 1 1-3.4-.2-.4A9.8 9.8 0 1 1 16 25.8Zm5.4-7.3c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2-.2.3-.8 1-.9 1.2-.2.2-.3.2-.6.1-1.8-.9-3-1.6-4.2-3.7-.3-.5.3-.5.9-1.7.1-.2.1-.5 0-.7-.1-.2-.7-1.7-1-2.3-.3-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.3-1.2 1.2-1.2 2.9s1.2 3.3 1.4 3.6c.2.2 2.4 3.7 5.9 5.2.8.4 1.5.6 2 .7.8.3 1.6.2 2.2.1.7-.1 1.8-.7 2.1-1.4.3-.7.3-1.3.2-1.4-.1-.2-.4-.3-.7-.5Z"/></svg>`;

function shell({ key, title, description, canonical, body, schema = '' }) {
  const nav = navItems.map(([href, label, itemKey]) => `<a href="${href}"${itemKey === key ? ' aria-current="page"' : ''}>${label}</a>`).join('');
  return `<!doctype html>
<html lang="it">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${title}</title>
<meta name="description" content="${description}">
<meta name="robots" content="index,follow,max-image-preview:large">
<meta name="theme-color" content="#07070a">
<link rel="canonical" href="${canonical}">
<meta property="og:type" content="website"><meta property="og:locale" content="it_IT"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${canonical}">
<link rel="stylesheet" href="/styles.css">
${schema}
</head>
<body>
<a class="skip-link" href="#contenuto">Vai al contenuto</a>
<header class="site-header"><div class="container nav-wrap"><a class="logo" href="/" aria-label="Axante, home"><img src="${logo}" width="198" height="76" alt="Axante"></a><nav class="nav" aria-label="Navigazione principale">${nav}</nav><a class="nav-cta" href="/contatti#audit">Audit gratuito <span>↗</span></a><button class="menu-toggle" type="button" aria-label="Apri il menu" aria-expanded="false"><span></span></button></div></header>
<main id="contenuto">${body}</main>
<footer class="site-footer"><div class="container"><div class="footer-grid"><div class="footer-brand"><img src="${logo}" width="198" height="76" alt="Axante"><p>Web agency e studio creativo a Roma. Strategia, design e tecnologia per trasformare la presenza digitale in crescita concreta.</p></div><div class="footer-col"><strong>Esplora</strong><a href="/servizi">Servizi</a><a href="/portfolio">Portfolio</a><a href="/chi-siamo">Chi siamo</a><a href="/lavora-con-noi">Lavora con noi</a></div><div class="footer-col"><strong>Servizi</strong><a href="/siti-web">Siti ed e-commerce</a><a href="/marketing">Marketing e social</a><a href="/branding">Brand e grafica</a><a href="/sviluppo">Sviluppo</a></div><div class="footer-col"><strong>Contatti</strong><a href="tel:+390633973984">06 3397 3984</a><a href="https://wa.me/393271706981">+39 327 170 6981</a><a href="mailto:hello@axante.it">hello@axante.it</a><span>Via Innocenzo XI, 40 · Roma</span></div></div><div class="footer-bottom"><span>© <span data-year>2026</span> Axante S.r.l. · P.IVA 16200861009</span><span>Axante è un marchio registrato · <a href="https://www.axante.it/privacy-policy/">Privacy Policy</a></span></div></div></footer>
<a class="whatsapp" href="https://wa.me/393271706981" target="_blank" rel="noopener" aria-label="Scrivi ad Axante su WhatsApp">${whatsappIcon}</a><script src="/script.js" defer></script>
</body></html>`;
}

function hero(eyebrow, title, text) {
  return `<section class="page-hero"><div class="container page-hero-grid"><div><span class="kicker reveal"><span class="kicker-dot"></span>${eyebrow}</span><h1 class="reveal">${title}</h1></div><p class="reveal">${text}</p></div></section>`;
}

function visual() {
  return `<div class="page-visual reveal"><i class="orb one"></i><i class="orb two"></i><div class="screen"><div class="screen-line w45"></div><div class="screen-line w70"></div><div class="screen-line"></div><div class="screen-cards"><i></i><i></i><i></i><i></i></div></div></div>`;
}

function cta(title = 'Il prossimo progetto può funzionare meglio.', text = 'Raccontaci cosa vuoi ottenere. Ti diremo con chiarezza cosa faremmo e da dove inizieremmo.') {
  return `<section><div class="container"><div class="cta-panel reveal"><span class="eyebrow">Parliamo del tuo obiettivo</span><h2>${title}</h2><p>${text}</p><div class="actions"><a class="btn btn-primary" href="/contatti#audit">Richiedi l’audit gratuito <span>↗</span></a><a class="btn btn-secondary" href="https://wa.me/393271706981">WhatsApp <span>→</span></a></div></div></div></section>`;
}

function writePage(slug, html) {
  const dir = path.join(site, slug);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'index.html'), html);
}

const serviceCards = [
  ['01','Siti Internet','Siti vetrina, blog, portali, landing page ed e-commerce responsive e su misura.','/siti-web'],
  ['02','Content creator','Foto, video, riprese aeree, reel, contenuti AI e materiale per campagne e canali proprietari.','/marketing#content'],
  ['03','Social media','Strategia, piano editoriale, produzione, pubblicazione, community e report.','/marketing#social'],
  ['04','Grafica','Grafica pubblicitaria, editoriale, istituzionale, impaginazione, fotoritocco e supporti fisici.','/branding#grafica'],
  ['05','SEO','Ricerca, architettura, contenuti e ottimizzazione tecnica per costruire visibilità organica.','/marketing#seo'],
  ['06','Logo e brand identity','Naming, logo, palette, tipografia, manuale e sistema visivo coerente.','/branding'],
  ['07','Advertising','Meta Ads, Google Ads, creatività, landing, tracking e ottimizzazione continua.','/marketing#advertising'],
  ['08','Consulenza digitale','Analisi indipendente per scegliere strumenti, priorità e investimenti senza sprechi.','/contatti#audit'],
  ['09','Strategia','Posizionamento, offerta, funnel e piano operativo collegati agli obiettivi economici.','/marketing'],
  ['10','Content marketing','Contenuti utili a costruire fiducia, domanda e autorevolezza nel tempo.','/marketing#content'],
  ['11','Stampa','Biglietti, brochure, riviste, libri, grande formato, gadget e coordinamento produzione.','/branding#stampa'],
  ['12','Development','Plugin, applicazioni web, app, gestionali, integrazioni e automazioni.','/sviluppo']
];

const servicesBody = `${hero('12 competenze, un solo partner','Tutto ciò che serve.<br><span class="gradient-text">Senza frammentare il progetto.</span>','Possiamo occuparci di una singola attività oppure costruire un sistema completo. Ogni servizio viene inserito solo quando serve davvero.')}
<section><div class="container"><div class="bento">${serviceCards.map(([n,t,p,l],i)=>`<article class="service-card ${i%3===0?'span-5':i%3===1?'span-7':'span-4'} reveal"><span class="service-no">${n}</span><span class="service-icon">${i%2?'↗':'◇'}</span><h3>${t}</h3><p>${p}</p><a class="btn btn-link" href="${l}">Approfondisci <span>→</span></a></article>`).join('')}</div></div></section>
<section><div class="container"><div class="price-card reveal"><div><span class="eyebrow">Pacchetti ore</span><h2>La competenza giusta,<br>solo per il tempo necessario.</h2><p>Un monte ore flessibile da utilizzare per richieste, interventi e consulenze diverse, senza moltiplicare fornitori e contratti.</p></div><div><strong>da 37,50€</strong><p>/ora + IVA</p><a class="btn btn-primary" href="/contatti">Richiedi disponibilità</a></div></div></div></section>${cta()}`;
writePage('servizi', shell({key:'servizi',title:'Servizi digitali per aziende e professionisti | Axante',description:'Siti web, e-commerce, SEO, social, advertising, grafica, brand identity, stampa, sviluppo e consulenza digitale.',canonical:'https://www.axante.it/servizi/',body:servicesBody}));

const portfolioCases = [
  ['carabetta','Carabetta','E-commerce · Fashion · UX/UI','Un’esperienza di acquisto elegante e immediata, progettata per valorizzare il prodotto senza rallentare il percorso verso la conversione.','https://www.axante.it/wp-content/uploads/2021/08/copertina-sito-carabetta.jpg'],
  ['unicart','Unicart Auctions','Marketplace · Aste online · Development','Un’interfaccia ordinata e una base tecnica capace di gestire registrazione, catalogo, offerte e dinamiche d’asta senza confusione.','https://www.axante.it/wp-content/uploads/2021/08/unicart.jpg'],
  ['weblab','WebLab TdA','Web design · Cultura · Editoriale','Una presenza digitale contemporanea per raccontare ricerca, formazione e cultura visiva con gerarchie chiare.','https://www.axante.it/wp-content/uploads/2021/08/weblab.jpg'],
  ['tda','Tracciati d’Arte','Magazine · Art direction · Content','Un ecosistema editoriale che mette al centro opere, autori e lettura, conservando identità e autorevolezza.','https://www.axante.it/wp-content/uploads/2021/08/tda.jpg']
];
const portfolioBody = `${hero('Selected work','Meno vetrina.<br><span class="gradient-text">Più sostanza.</span>','Ogni progetto nasce da un problema diverso. Per questo non replichiamo una formula: costruiamo identità, percorsi e tecnologie intorno alle persone che dovranno usarli.')}
<section class="portfolio-hero"><div class="container portfolio-list">${portfolioCases.map(([id,t,tags,p,img])=>`<article class="case-row reveal" id="${id}"><div class="case-media"><img src="${img}" width="1200" height="800" loading="lazy" alt="${t}"></div><div class="case-copy"><span class="eyebrow">${tags}</span><h2>${t}</h2><p>${p}</p><a class="btn btn-link" href="/contatti">Voglio un progetto così <span>→</span></a></div></article>`).join('')}</div></section>${cta('Costruiamo il prossimo caso studio.','Un progetto riuscito non deve sembrare Axante: deve sembrare inevitabilmente tuo e funzionare per il tuo pubblico.')}`;
writePage('portfolio', shell({key:'portfolio',title:'Portfolio web, e-commerce e brand | Axante',description:'Scopri alcuni progetti Axante: e-commerce, marketplace, siti editoriali, brand e prodotti digitali progettati per funzionare.',canonical:'https://www.axante.it/portfolio/',body:portfolioBody}));

const aboutBody = `${hero('Strategia, design, tecnologia','Le persone dietro<br><span class="gradient-text">i risultati.</span>','Siamo fornitori di servizi digitali, ma sarebbero inutili se non portassero risultati concreti e quantificabili. Per questo lavoriamo con curiosità, metodo e responsabilità.')}
<section><div class="container content-grid"><div class="sticky-copy"><span class="eyebrow">Il nostro modo di lavorare</span><h2>Il tuo sogno.<br>La nostra missione.</h2><p>Ogni realtà ha punti forti, vincoli e opportunità diverse. Studiamo il contesto, scegliamo gli strumenti e rendiamo semplice anche ciò che tecnicamente non lo è.</p></div><div class="feature-list"><article class="feature reveal"><small>01 · ESPLORARE</small><h3>Restiamo curiosi</h3><p>Internet cambia ogni giorno. Aggiornamenti, strumenti e nuovi comportamenti sono parte del lavoro, non un fastidio.</p></article><article class="feature reveal"><small>02 · COSTRUIRE</small><h3>Step-by-step</h3><p>Obiettivi ambiziosi diventano gestibili quando sono divisi in priorità, fasi e verifiche chiare.</p></article><article class="feature reveal"><small>03 · SEMPLIFICARE</small><h3>La complessità resta dietro</h3><p>Processi, interfacce e comunicazione devono risultare semplici per il cliente e per l’utente finale.</p></article></div></div></section>
<section><div class="container"><div class="section-head"><div><span class="eyebrow">Team</span><h2>Responsabilità chiare.<br>Competenze che collaborano.</h2></div><p>Il referente del progetto coordina le figure specialistiche e rimane il punto di contatto lungo tutto il percorso.</p></div><div class="team-grid"><article class="team-card reveal"><div class="avatar">DB</div><h3>Daniele</h3><span>Project Manager</span><p>Strategia, coordinamento, offerta e trasformazione degli obiettivi in un piano realizzabile.</p></article><article class="team-card reveal"><div class="avatar">EL</div><h3>Elias</h3><span>Web Designer</span><p>Esperienza utente, design delle interfacce e cura della resa su ogni dispositivo.</p></article><article class="team-card reveal"><div class="avatar">CR</div><h3>Creative team</h3><span>Design & Content</span><p>Identità, grafica, shooting, video e contenuti per rendere il brand riconoscibile.</p></article><article class="team-card reveal"><div class="avatar">DV</div><h3>Development</h3><span>Tech & Automation</span><p>Sviluppo, integrazioni e soluzioni su misura per collegare strumenti e processi.</p></article></div></div></section>
<section><div class="container"><div class="values"><article class="value-card reveal"><b>DESIGN</b><h3>Amiamo il bello</h3><p>La forma deve aumentare chiarezza, desiderabilità e credibilità.</p></article><article class="value-card reveal"><b>RISULTATI</b><h3>Misuriamo ciò che conta</h3><p>Report, fatturato, lead, tempo risparmiato e obiettivi concordati.</p></article><article class="value-card reveal"><b>AFFIDABILITÀ</b><h3>Diciamo anche no</h3><p>Accettiamo i progetti che possiamo seguire bene e nelle tempistiche stabilite.</p></article></div></div></section>${cta('Il team giusto parte dalle domande giuste.','Raccontaci il progetto, anche se è ancora soltanto un’idea. Il primo confronto è gratuito e senza impegno.')}`;
writePage('chi-siamo', shell({key:'chi-siamo',title:'Chi siamo | Axante Web Agency Roma',description:'Conosci il team e il metodo Axante: strategia, design, tecnologia e orientamento ai risultati concreti.',canonical:'https://www.axante.it/chi-siamo/',body:aboutBody}));

const contactBody = `${hero('Contatto diretto','Parliamo del tuo<br><span class="gradient-text">prossimo risultato.</span>','Niente centralini o percorsi complicati. Raccontaci obiettivo, problema o idea: risponderemo con domande e priorità concrete.')}
<section id="audit"><div class="container contact-layout"><aside class="contact-info reveal"><span class="eyebrow">Axante · Roma</span><h2>Scegli il canale più comodo.</h2><div class="contact-links"><a class="contact-link" href="https://wa.me/393271706981"><span>WhatsApp</span><strong>+39 327 170 6981 ↗</strong></a><a class="contact-link" href="tel:+390633973984"><span>Telefono</span><strong>06 3397 3984</strong></a><a class="contact-link" href="mailto:hello@axante.it"><span>Email</span><strong>hello@axante.it</strong></a><div class="contact-link"><span>Sede</span><strong>Via Innocenzo XI, 40 · 00165 Roma</strong></div></div><p class="contact-note">Il primo confronto è gratuito. Per le urgenze dei clienti attivi è disponibile assistenza dedicata.</p></aside><form class="contact-form reveal" data-whatsapp-form><span class="eyebrow">Audit gratuito</span><h2>Partiamo da qui.</h2><div class="form-grid"><div class="field"><label for="name">Nome *</label><input id="name" name="name" autocomplete="name" required></div><div class="field"><label for="phone">Telefono *</label><input id="phone" name="phone" autocomplete="tel" required></div><div class="field"><label for="company">Azienda o progetto</label><input id="company" name="company"></div><div class="field"><label for="service">Area di interesse</label><select id="service" name="service"><option value="">Seleziona</option><option>Sito web / e-commerce</option><option>Marketing / advertising</option><option>Social e contenuti</option><option>Brand identity / grafica</option><option>Sviluppo / automazioni</option><option>Consulenza generale</option></select></div><div class="field full"><label for="budget">Budget indicativo</label><select id="budget" name="budget"><option value="">Preferisco parlarne</option><option>Fino a 2.000€</option><option>2.000€ – 5.000€</option><option>5.000€ – 10.000€</option><option>Oltre 10.000€</option></select></div><div class="field full"><label for="message">Obiettivo o problema principale *</label><textarea id="message" name="message" required placeholder="Cosa vuoi ottenere? Cosa oggi non sta funzionando?"></textarea></div></div><div class="form-footer"><p class="form-status">Il form apre WhatsApp con il messaggio già compilato.</p><button class="btn btn-primary" type="submit">Invia la richiesta <span>↗</span></button></div></form></div></section>`;
writePage('contatti', shell({key:'contatti',title:'Contatti e audit digitale gratuito | Axante Roma',description:'Contatta Axante a Roma e richiedi un audit gratuito per siti, e-commerce, marketing, social, branding o sviluppo.',canonical:'https://www.axante.it/contatti/',body:contactBody}));

const websitesBody = `${hero('Siti ed e-commerce','Un sito non deve<br><span class="gradient-text">soltanto esistere.</span>','Deve caricarsi velocemente, spiegare bene, costruire fiducia e guidare l’utente verso un’azione. Tutto il resto è decorazione.')}
<section><div class="container content-grid"><div class="sticky-copy">${visual()}</div><div class="feature-list"><article class="feature reveal"><small>01 · STRATEGIA</small><h3>Architettura basata sulle intenzioni</h3><p>Pagine, messaggi e percorsi nascono da ciò che le persone cercano e devono capire prima di contattarti o acquistare.</p></article><article class="feature reveal"><small>02 · DESIGN</small><h3>Un’identità, non un template</h3><p>Interfacce originali e coerenti con il posizionamento, ottimizzate per mobile e accessibili.</p></article><article class="feature reveal"><small>03 · PERFORMANCE</small><h3>Velocità, SEO e tracciamento</h3><p>Fondamenta tecniche solide, dati misurabili e attenzione alle Core Web Vitals.</p></article><article class="feature reveal"><small>04 · CONTINUITÀ</small><h3>Garanzia e assistenza</h3><p>Garanzia minima di un anno sui siti e supporto per manutenzione, crescita ed evoluzione.</p></article></div></div></section>
<section><div class="container"><div class="section-head"><div><span class="eyebrow">Soluzioni</span><h2>Dalla presenza essenziale<br>al prodotto digitale.</h2></div><p>Sito vetrina, professionale, blog, portale, e-commerce, marketplace o piattaforma personalizzata.</p></div><div class="values"><article class="value-card reveal"><b>VETRINA</b><h3>Presenta e convince</h3><p>Per professionisti e aziende che devono trasformare la reputazione in richieste.</p></article><article class="value-card reveal"><b>E-COMMERCE</b><h3>Vende senza attrito</h3><p>Catalogo, pagamenti, spedizioni, tracking, automazioni e integrazioni gestionali.</p></article><article class="value-card reveal"><b>CUSTOM</b><h3>Fa ciò che serve</h3><p>Portali, marketplace, aree riservate e flussi progettati intorno al modello operativo.</p></article></div></div></section>${cta('Il tuo sito può diventare uno strumento commerciale.','Partiamo con un audit di sito, mercato e percorso utente. Nessun preventivo preconfezionato.')}`;
writePage('siti-web', shell({key:'servizi',title:'Creazione siti web ed e-commerce a Roma | Axante',description:'Siti web, e-commerce, portali e landing page su misura: veloci, responsive, SEO-ready e progettati per convertire.',canonical:'https://www.axante.it/creazione-siti-web/',body:websitesBody}));

const marketingBody = `${hero('Growth, social e contenuti','Attenzione non basta.<br><span class="gradient-text">Serve direzione.</span>','Colleghiamo strategia, creatività, campagne, SEO e misurazione per trasformare visibilità in domanda e domanda in clienti.')}
<section><div class="container"><div class="bento"><article class="service-card span-7 reveal" id="advertising"><span class="service-no">01 · ADVERTISING</span><span class="service-icon">↗</span><h3>Meta Ads e Google Ads</h3><p>Ricerca, creatività, landing, tracking e ottimizzazione. Il budget viene distribuito in base ai dati, non alle abitudini.</p><a class="btn btn-link" href="/contatti">Analizziamo le campagne <span>→</span></a></article><article class="service-card span-5 reveal" id="social"><span class="service-no">02 · SOCIAL MEDIA</span><span class="service-icon">◎</span><h3>Strategia e community</h3><p>Format, piano editoriale, produzione, pubblicazione e community management collegati al posizionamento.</p></article><article class="service-card span-4 reveal" id="seo"><span class="service-no">03 · SEO</span><span class="service-icon">⌕</span><h3>Visibilità organica</h3><p>Ricerca, struttura, contenuti, ottimizzazione on-page e interventi tecnici.</p></article><article class="service-card span-4 reveal" id="content"><span class="service-no">04 · CONTENT</span><span class="service-icon">◇</span><h3>Foto, video e reel</h3><p>Shooting, video, creator, contenuti AI e asset pubblicitari pensati per il canale.</p></article><article class="service-card span-4 reveal"><span class="service-no">05 · STRATEGY</span><span class="service-icon">⌘</span><h3>Offerta e funnel</h3><p>Posizionamento, leve, percorso commerciale e priorità per rendere il marketing coerente.</p></article></div></div></section>
<section><div class="container"><div class="results-panel reveal"><span class="eyebrow">Report che servono</span><h2>Non solo visualizzazioni.<br>Leggiamo ciò che muove il business.</h2><div class="stats"><div class="stat"><strong>ROI</strong><span>ritorno sull’investimento</span></div><div class="stat"><strong>CPL</strong><span>costo per contatto utile</span></div><div class="stat"><strong>CVR</strong><span>tasso di conversione</span></div><div class="stat"><strong>LTV</strong><span>valore nel tempo</span></div></div></div></div></section>${cta('Trasformiamo il marketing in un sistema.','Possiamo analizzare campagne, canali, tracciamento e proposta per identificare sprechi e opportunità.')}`;
writePage('marketing', shell({key:'servizi',title:'Marketing digitale, social, SEO e advertising | Axante',description:'Strategia digitale, Meta Ads, Google Ads, social media, content creator, SEO, funnel e misurazione orientata al ROI.',canonical:'https://www.axante.it/servizi/',body:marketingBody}));

const brandingBody = `${hero('Brand e comunicazione visiva','Riconoscibile prima.<br><span class="gradient-text">Credibile subito.</span>','Un buon brand non è soltanto un logo: è un sistema di scelte coerenti che rende più semplice farsi ricordare, capire e scegliere.')}
<section><div class="container content-grid"><div class="sticky-copy">${visual()}</div><div class="feature-list"><article class="feature reveal"><small>01 · IDENTITÀ</small><h3>Logo e brand identity</h3><p>Ricerca, posizionamento, concept, logo vettoriale, palette, tipografia, icone, mockup e linee guida.</p></article><article class="feature reveal" id="grafica"><small>02 · COMUNICAZIONE</small><h3>Grafica a 360°</h3><p>Social, advertising, editoriale, istituzionale, presentazioni, packaging, fotoritocco e veicoli commerciali.</p></article><article class="feature reveal" id="stampa"><small>03 · PRODUZIONE</small><h3>Stampa e materiali fisici</h3><p>Biglietti, brochure, libri, riviste, striscioni, grande formato, gadget e coordinamento con la tipografia.</p></article><article class="feature reveal"><small>04 · COERENZA</small><h3>Un sistema che il team sa usare</h3><p>Template, librerie e regole operative per mantenere qualità e riconoscibilità nel tempo.</p></article></div></div></section>${cta('Il brand deve parlare prima delle parole.','Mostraci ciò che esiste oggi e raccontaci dove vuoi arrivare. Costruiremo una direzione visiva utilizzabile, non soltanto bella.')}`;
writePage('branding', shell({key:'servizi',title:'Logo, brand identity e studio grafico Roma | Axante',description:'Logo design, brand identity, grafica pubblicitaria, editoriale, stampa, packaging e sistemi visivi per aziende e professionisti.',canonical:'https://www.axante.it/servizi/studio-grafico-roma/',body:brandingBody}));

const developmentBody = `${hero('Development e automazioni','La tecnologia giusta.<br><span class="gradient-text">Non quella di moda.</span>','Sviluppiamo funzioni, integrazioni e prodotti digitali intorno al processo reale, riducendo attività manuali e colli di bottiglia.')}
<section><div class="container"><div class="bento"><article class="service-card span-7 reveal"><span class="service-no">01 · WEB APP</span><span class="service-icon">&lt;/&gt;</span><h3>Applicazioni e piattaforme</h3><p>Aree riservate, marketplace, prenotazioni, dashboard, portali e prodotti SaaS progettati per utenti e operatori.</p></article><article class="service-card span-5 reveal"><span class="service-no">02 · WORDPRESS</span><span class="service-icon">W</span><h3>Plugin e temi personalizzati</h3><p>Funzionalità su misura, WooCommerce, integrazioni e interventi su progetti esistenti.</p></article><article class="service-card span-4 reveal"><span class="service-no">03 · AUTOMATION</span><span class="service-icon">⚡</span><h3>Flussi automatici</h3><p>CRM, email, documenti, lead, notifiche e operazioni ripetitive collegate tra loro.</p></article><article class="service-card span-4 reveal"><span class="service-no">04 · INTEGRATION</span><span class="service-icon">↔</span><h3>API e sistemi</h3><p>Pagamenti, gestionali, marketplace, database, strumenti marketing e servizi esterni.</p></article><article class="service-card span-4 reveal"><span class="service-no">05 · AI</span><span class="service-icon">✦</span><h3>AI applicata</h3><p>Assistenti, classificazione, generazione e processi intelligenti con controllo umano dove serve.</p></article></div></div></section>
<section><div class="container"><div class="section-head"><div><span class="eyebrow">Prima il processo</span><h2>Automatizzare un caos<br>crea un caos più veloce.</h2></div><p>Mappiamo attività, eccezioni e responsabilità prima di scegliere strumenti e scrivere codice.</p></div><div class="process-grid"><article class="process-card reveal"><span class="process-step">01</span><h3>Mappa</h3><p>Capire persone, dati, strumenti e passaggi attuali.</p></article><article class="process-card reveal"><span class="process-step">02</span><h3>Semplifica</h3><p>Eliminare ciò che non serve prima di automatizzarlo.</p></article><article class="process-card reveal"><span class="process-step">03</span><h3>Costruisci</h3><p>Integrare in moduli verificabili e documentati.</p></article><article class="process-card reveal"><span class="process-step">04</span><h3>Monitora</h3><p>Log, controlli e manutenzione per evitare sorprese.</p></article></div></div></section>${cta('Raccontaci il collo di bottiglia.','Una breve analisi può chiarire se serve sviluppo personalizzato, un’integrazione o semplicemente un processo migliore.')}`;
writePage('sviluppo', shell({key:'servizi',title:'Sviluppo software, web app e automazioni | Axante',description:'Sviluppo web app, plugin WordPress, piattaforme, API, integrazioni, gestionali e automazioni per aziende.',canonical:'https://www.axante.it/servizi/',body:developmentBody}));

const careersBody = `${hero('Lavora con noi','Cerchiamo persone<br><span class="gradient-text">che fanno accadere le cose.</span>','Collaboriamo con professionisti curiosi, affidabili e capaci di unire qualità del lavoro e rispetto delle scadenze.')}
<section><div class="container"><div class="career-grid"><article class="career-card reveal"><small>DESIGN</small><h3>Web & graphic designer</h3><p>Interfacce, brand, campagne e sistemi visivi. Portfolio e capacità di spiegare le scelte sono essenziali.</p><a class="btn btn-link" href="mailto:hello@axante.it?subject=Candidatura%20Design">Candidati <span>→</span></a></article><article class="career-card reveal"><small>CONTENT</small><h3>Creator e videomaker</h3><p>Riprese, montaggio, format verticali e capacità di adattare il linguaggio al progetto.</p><a class="btn btn-link" href="mailto:hello@axante.it?subject=Candidatura%20Content">Candidati <span>→</span></a></article><article class="career-card reveal"><small>TECH</small><h3>Developer e automation specialist</h3><p>Web, WordPress, API, database e automazioni. Cerchiamo problem solver, non collezionisti di framework.</p><a class="btn btn-link" href="mailto:hello@axante.it?subject=Candidatura%20Development">Candidati <span>→</span></a></article></div></div></section>${cta('Non vedi il ruolo perfetto?','Invia comunque una presentazione concreta e alcuni lavori. Le collaborazioni migliori spesso iniziano prima della posizione ufficiale.')}`;
writePage('lavora-con-noi', shell({key:'chi-siamo',title:'Lavora con noi | Axante',description:'Opportunità di collaborazione con Axante per designer, creator, videomaker, developer e specialisti digitali.',canonical:'https://www.axante.it/lavora-con-noi/',body:careersBody}));

const notFoundBody = `${hero('Errore 404','Questa pagina<br><span class="gradient-text">non è qui.</span>','Il link potrebbe essere cambiato oppure la pagina non esiste più. Torna alla home o raccontaci cosa stavi cercando.')}<section><div class="container"><div class="actions"><a class="btn btn-primary" href="/">Torna alla home</a><a class="btn btn-secondary" href="/contatti">Contattaci</a></div></div></section>`;
fs.writeFileSync(path.join(site,'404.html'), shell({key:'',title:'Pagina non trovata | Axante',description:'La pagina richiesta non è disponibile.',canonical:'https://www.axante.it/404',body:notFoundBody}).replace('index,follow,max-image-preview:large','noindex,follow'));

const urls = ['','servizi/','portfolio/','chi-siamo/','contatti/','siti-web/','marketing/','branding/','sviluppo/','lavora-con-noi/'];
fs.writeFileSync(path.join(site,'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(url=>`  <url><loc>https://www.axante.it/${url}</loc><changefreq>${url?'monthly':'weekly'}</changefreq><priority>${url?'0.8':'1.0'}</priority></url>`).join('\n')}\n</urlset>`);
fs.writeFileSync(path.join(site,'robots.txt'), 'User-agent: *\nAllow: /\nSitemap: https://www.axante.it/sitemap.xml\n');
fs.writeFileSync(path.join(site,'site.webmanifest'), JSON.stringify({name:'Axante',short_name:'Axante',start_url:'/',display:'standalone',background_color:'#07070a',theme_color:'#07070a'},null,2));
console.log('Generated commercial pages, SEO files and error page.');
